"""Insider-drift demo.

Picks entities that legitimately expanded their resource footprint (generated by
data_gen as label="normal", tracked in data/drift_entities.json) and shows their risk
signals over time -- confirming the footprint change alone doesn't sustain a flag --
plus a description of the feedback/retraining loop that would let the system adapt.
"""

import json

import numpy as np
import pandas as pd

from features.feature_engineering import FEATURE_COLUMNS
from models.anomaly_detector import AnomalyDetector
from models.attack_classifier import AttackClassifier

DRIFT_ENTITIES_PATH = "data/drift_entities.json"
FEATURES_PATH = "data/features.csv"
N_DEMO_ENTITIES = 2


def _longest_streak(bool_series):
    longest = current = 0
    for val in bool_series:
        if val:
            current += 1
            longest = max(longest, current)
        else:
            current = 0
    return longest


def _score_entity_timeline(entity_id, features_df, detector, classifier):
    entity_df = features_df[features_df["user_id"] == entity_id].sort_values("timestamp").reset_index(drop=True)
    X = entity_df[FEATURE_COLUMNS]
    probs = classifier.predict_proba(X)
    classes = classifier.model.classes_
    max_idx = probs.argmax(axis=1)
    entity_df = entity_df.assign(
        anomaly_score=detector.score(X),
        classifier_pred=classes[max_idx],
        classifier_confidence=probs[np.arange(len(probs)), max_idx],
    )
    entity_df["would_flag"] = (entity_df["classifier_pred"] != "normal") & (entity_df["classifier_confidence"] > 0.5)
    return entity_df


def main():
    with open(DRIFT_ENTITIES_PATH) as f:
        drift_records = json.load(f)

    print("=== Insider Drift Demo ===")
    print(f"{len(drift_records)} entities tracked as legitimate drift in {DRIFT_ENTITIES_PATH}\n")

    features_df = pd.read_csv(FEATURES_PATH, parse_dates=["timestamp"])
    detector = AnomalyDetector.load()
    classifier = AttackClassifier.load()

    for record in drift_records[:N_DEMO_ENTITIES]:
        entity_id = record["entity_id"]
        print(f"--- {entity_id} ({record['entity_type']}) ---")
        print(f"Drift window: {record['drift_start']} to {record['drift_end']}")
        print(f"Resources added: {record['resources_added']}")
        print(f"Drift events generated: {record['n_drift_events']}\n")

        timeline = _score_entity_timeline(entity_id, features_df, detector, classifier)
        drift_start, drift_end = pd.Timestamp(record["drift_start"]), pd.Timestamp(record["drift_end"])
        in_drift = timeline[(timeline["timestamp"] >= drift_start) & (timeline["timestamp"] <= drift_end)]
        non_normal = in_drift[in_drift["classifier_pred"] != "normal"]

        print(f"Events in drift window: {len(in_drift)} (of {len(timeline)} total for this entity)")
        print(f"  mean anomaly_score in window:  {in_drift['anomaly_score'].mean():.4f}"
              f"   (entity-wide mean: {timeline['anomaly_score'].mean():.4f})")
        if len(non_normal):
            print(f"  mean confidence on the {len(non_normal)} non-normal predictions: "
                  f"{non_normal['classifier_confidence'].mean():.4f}")
        else:
            print("  classifier predicted 'normal' for every single drift-window event")
        print(f"  would_flag (classifier confidence > 0.5 on a non-normal label): "
              f"{int(in_drift['would_flag'].sum())} / {len(in_drift)}")
        print(f"  longest consecutive would_flag streak: {_longest_streak(in_drift['would_flag'])}\n")

    print(
        "Conclusion: resource-footprint expansion alone does not sustain a flag -- isolated\n"
        "would_flag hits (if any) don't chain into a persistent 'this entity is compromised'\n"
        "verdict, because both the classifier and anomaly detector key off point-in-time\n"
        "deviation from the *original* baseline, not a running streak counter.\n"
    )

    print("=== Feedback / retraining mechanism ===\n")
    print(
        "If an analyst repeatedly marks a drifted entity's alerts \"false_positive\" via the\n"
        "dashboard's verdict buttons (data/feedback.csv), that signal is ready for the next retrain:\n\n"
        "  1. Periodic retrain re-runs models/train.py on an updated chronological window -- since\n"
        "     each entity's baseline is always \"the first 60% of THAT entity's own recent history,\"\n"
        "     a role change or new project (like these drift entities) ages into the baseline\n"
        "     automatically once enough time has passed for it to dominate the entity's history.\n"
        "  2. Confirmed false positives from feedback.csv could be spliced directly into the next\n"
        "     baseline-building pass, so the newly-adopted resources stop being flagged as \"new\"\n"
        "     well before the natural chronological rollover would catch up.\n"
        "  3. Confirmed threats do the opposite -- excluded from ever entering a baseline, so an\n"
        "     attacker's early reconnaissance can't get absorbed as \"normal\" just because it\n"
        "     happened early in the window.\n\n"
        "This keeps the system's notion of \"normal\" moving with real organizational change\n"
        "without requiring a manual allowlist per entity."
    )


if __name__ == "__main__":
    main()
