"""Insider-drift demo.

Picks entities that legitimately expanded their resource footprint (generated by
data_gen as label="normal", tracked in data/drift_entities.json) and shows their real
hybrid-alert-rule behavior over time -- confirming the footprint change alone doesn't
sustain a flag -- plus a description of the feedback/retraining loop that would let the
system adapt.

Entity selection prefers label-pure entities: ones whose entire drift window is
genuinely label=="normal", with no coincidental unrelated real attack landing in the
same date range. Only 1 of the 12 tracked drift entities (user_0140) is fully clean --
the rest each have 2-9 events from a real, independently-injected attack overlapping
their drift window (a realistic artifact of continuous background activity, not a bug;
see README's Known Limitations). Confounded entities are only ever used as a clearly
labeled secondary example, never presented as clean.

Depends on artifacts trained by the current models/train.py (post train/val/test split) --
rerun `python -m models.train` first if the saved anomaly detector / classifier / sequence
detector are stale.
"""

import json

import numpy as np
import pandas as pd

from features.feature_engineering import FEATURE_COLUMNS
from models.anomaly_detector import AnomalyDetector
from models.attack_classifier import AttackClassifier
from models.sequence_detector import SequenceAnomalyDetector
from models.train import (
    DEFAULT_CONFIG, _confusion_rates, compute_signals, load_splits, sweep_safety_net_thresholds,
)

DRIFT_ENTITIES_PATH = "data/drift_entities.json"
FEATURES_PATH = "data/features.csv"
N_DEMO_ENTITIES = 2


def _run_lengths(bool_list):
    """Consecutive-True run lengths, in order. [] if no True at all."""
    runs, i = [], 0
    while i < len(bool_list):
        if bool_list[i]:
            j = i
            while j < len(bool_list) and bool_list[j]:
                j += 1
            runs.append(j - i)
            i = j
        else:
            i += 1
    return runs


def _frozen_safety_net_thresholds(config, detector, classifier, seq_score_lookup, val_df):
    """Reproduces the exact IF/sequence safety-net thresholds models.train.main() freezes
    from validation. Duplicated here (read-only, same logic) rather than imported, since
    train.py doesn't persist these values anywhere after a training run completes."""
    val_sig = compute_signals(val_df, detector, classifier, seq_score_lookup)
    classifier_alert_val = (val_sig["y_pred"] != "normal") & (val_sig["max_prob"] > config["classifier_prob_cutoff"])
    sweep_cfg = config["safety_net_sweep"]
    sweep_df, sweep_thresholds = sweep_safety_net_thresholds(
        val_sig["anomaly_scores"], val_sig["sequence_scores"], classifier_alert_val, val_sig["is_attack"],
        sweep_cfg["if_percentiles"], sweep_cfg["sequence_percentiles"],
    )
    if_alert_default_val = val_sig["anomaly_scores"] >= np.percentile(val_sig["anomaly_scores"], config["if_high_confidence_percentile"])
    seq_alert_default_val = val_sig["sequence_scores"] >= np.percentile(val_sig["sequence_scores"], config["sequence_high_confidence_percentile"])
    hybrid_alerted_default_val = classifier_alert_val | if_alert_default_val | seq_alert_default_val
    current_detection = _confusion_rates(hybrid_alerted_default_val, val_sig["is_attack"])["detection_rate"]
    eligible = sweep_df[sweep_df["detection_rate"] >= current_detection - sweep_cfg["detection_tolerance"]]
    if eligible.empty:
        eligible = sweep_df
    best_row = eligible.loc[eligible["precision"].idxmax()]
    chosen_if_pct = 100 - best_row["if_top_pct"]
    chosen_seq_pct = 100 - best_row["seq_top_pct"]
    return sweep_thresholds[(chosen_if_pct, chosen_seq_pct)]


def _score_entity_timeline(entity_id, features_df, detector, classifier, seq_score_lookup, if_thr, seq_thr, classifier_cutoff):
    entity_df = features_df[features_df["user_id"] == entity_id].sort_values("timestamp").reset_index(drop=True)
    X = entity_df[FEATURE_COLUMNS]
    probs = classifier.predict_proba(X)
    classes = classifier.model.classes_
    max_idx = probs.argmax(axis=1)
    entity_df = entity_df.assign(
        anomaly_score=detector.score(X),
        sequence_score=entity_df["event_id"].map(seq_score_lookup),
        classifier_pred=classes[max_idx],
        classifier_confidence=probs[np.arange(len(probs)), max_idx],
    )
    entity_df["classifier_alert"] = (entity_df["classifier_pred"] != "normal") & (entity_df["classifier_confidence"] > classifier_cutoff)
    entity_df["if_alert"] = entity_df["anomaly_score"] >= if_thr
    entity_df["seq_alert"] = entity_df["sequence_score"] >= seq_thr
    # the REAL hybrid alert rule -- the same one models/train.py freezes from validation and
    # applies to the test set, not a classifier-confidence-only proxy. An earlier version of
    # this demo used such a proxy ("would_flag"); it undercounted real alerts and once made a
    # coincidental true positive on an unrelated attack look like a possible false positive.
    entity_df["alerted"] = entity_df["classifier_alert"] | entity_df["if_alert"] | entity_df["seq_alert"]
    return entity_df


def _label_purity(entity_id, drift_start, drift_end, features_df):
    """Returns (n_non_normal_events, label_counts_dict) for an entity's drift window."""
    ds, de = pd.Timestamp(drift_start), pd.Timestamp(drift_end)
    entity = features_df[features_df["user_id"] == entity_id]
    window = entity[(entity["timestamp"] >= ds) & (entity["timestamp"] <= de)]
    label_counts = window["label"].value_counts().to_dict()
    n_non_normal = int(window[window["label"] != "normal"].shape[0])
    return n_non_normal, label_counts


def _select_demo_entities(drift_records, features_df):
    """Prefer label-pure entities (100% true label=="normal" in the drift window) so the
    demo's printed false-positive rate isn't confounded by a coincidental, unrelated real
    attack landing inside the same date window. Falls back to the least-confounded entities,
    clearly flagged as such, only when fewer than N_DEMO_ENTITIES clean ones exist.
    """
    scored = [(rec, *_label_purity(rec["entity_id"], rec["drift_start"], rec["drift_end"], features_df)) for rec in drift_records]
    clean = [t for t in scored if t[1] == 0]
    confounded = sorted((t for t in scored if t[1] > 0), key=lambda t: t[1])
    selected = clean[:N_DEMO_ENTITIES]
    if len(selected) < N_DEMO_ENTITIES:
        selected += confounded[: N_DEMO_ENTITIES - len(selected)]
    return selected  # list of (record, n_non_normal, label_counts) -- clean entries first


def main():
    with open(DRIFT_ENTITIES_PATH) as f:
        drift_records = json.load(f)

    print("=== Insider Drift Demo ===")
    print(f"{len(drift_records)} entities tracked as legitimate drift in {DRIFT_ENTITIES_PATH}\n")

    features_df = pd.read_csv(FEATURES_PATH, parse_dates=["timestamp"])
    detector = AnomalyDetector.load()
    classifier = AttackClassifier.load()
    seq_detector = SequenceAnomalyDetector.load()

    config = DEFAULT_CONFIG
    train_df, val_df, test_df = load_splits(config)
    full_df = pd.concat([train_df, val_df, test_df], ignore_index=True)
    seq_score_lookup = seq_detector.score(full_df)
    if_thr, seq_thr = _frozen_safety_net_thresholds(config, detector, classifier, seq_score_lookup, val_df)
    print(
        f"Real hybrid alert rule, frozen thresholds from validation: IF >= {if_thr:.4f}, "
        f"sequence >= {seq_thr:.4f}, classifier_prob > {config['classifier_prob_cutoff']} "
        f"-- the same rule models/train.py applies to the test set.\n"
    )

    selected = _select_demo_entities(drift_records, features_df)
    n_clean_selected = sum(1 for _, n, _ in selected if n == 0)
    n_clean_total = sum(1 for rec in drift_records if _label_purity(rec["entity_id"], rec["drift_start"], rec["drift_end"], features_df)[0] == 0)
    print(
        f"Entity selection: {n_clean_selected}/{N_DEMO_ENTITIES} selected entities are fully label-pure "
        f"(only {n_clean_total}/{len(drift_records)} tracked entities are -- the rest each have a real, "
        f"independently-injected attack coincidentally overlapping their drift window).\n"
    )

    fp_summaries = []
    for record, n_non_normal, label_counts in selected:
        entity_id = record["entity_id"]
        is_clean = n_non_normal == 0
        tag = "CLEAN -- 100% genuine drift/normal behavior" if is_clean else "CONTAINS A COINCIDENTAL REAL ATTACK"
        print(f"--- {entity_id} ({record['entity_type']}) [{tag}] ---")
        print(f"Drift window: {record['drift_start']} to {record['drift_end']}")
        print(f"Resources added: {record['resources_added']}")
        print(f"Drift events generated: {record['n_drift_events']}")
        print(f"True-label breakdown in window: {label_counts}")

        timeline = _score_entity_timeline(
            entity_id, features_df, detector, classifier, seq_score_lookup, if_thr, seq_thr, config["classifier_prob_cutoff"]
        )
        ds, de = pd.Timestamp(record["drift_start"]), pd.Timestamp(record["drift_end"])
        in_window = timeline[(timeline["timestamp"] >= ds) & (timeline["timestamp"] <= de)].reset_index(drop=True)

        alerted_seq = in_window["alerted"].tolist()
        runs = _run_lengths(alerted_seq)
        n_alerted = int(sum(alerted_seq))

        if is_clean:
            fp_rate = n_alerted / len(in_window) if len(in_window) else 0.0
            print(f"Events in window: {len(in_window)} (all true-label normal)")
            print(f"Alerted (real hybrid rule): {n_alerted} / {len(in_window)}  |  run lengths: {runs}")
            print(f"False-positive rate on genuine drift behavior: {fp_rate:.4f} ({fp_rate:.2%})")
            fp_summaries.append((entity_id, fp_rate, runs, True))
        else:
            # Explain itself rather than looking like a bug: separate true positives on the
            # coincidental real attack from any genuine false positives on the normal-labeled
            # drift events, matching exactly what was manually verified for this entity.
            in_window_normal = in_window[in_window["label"] == "normal"]
            in_window_attack = in_window[in_window["label"] != "normal"]
            fp_on_normal = int(in_window_normal["alerted"].sum())
            tp_on_attack = int(in_window_attack["alerted"].sum())
            fp_rate = fp_on_normal / len(in_window_normal) if len(in_window_normal) else 0.0
            print(f"Events in window: {len(in_window)} ({len(in_window_normal)} normal, {len(in_window_attack)} coincidental real attack)")
            print(f"Alerted (real hybrid rule): {n_alerted} / {len(in_window)}  |  run lengths: {runs}")
            print(f"  of which {tp_on_attack}/{len(in_window_attack)} are TRUE POSITIVES on the coincidental "
                  f"real attack (correct detection, not a drift false alarm)")
            print(f"  of which {fp_on_normal}/{len(in_window_normal)} are genuine false positives on true-normal "
                  f"drift events -- false-positive rate: {fp_rate:.4f} ({fp_rate:.2%})")
            print("  Shown for completeness only (just 1 fully clean entity exists in the tracked list); "
                  "judge this entity's drift behavior by the false-positive-on-normal-events rate above, "
                  "not the raw alert count, which is mostly a real unrelated attack being caught correctly.")
            fp_summaries.append((entity_id, fp_rate, runs, False))
        print()

    print("=== Conclusion ===")
    for entity_id, fp_rate, runs, is_clean in fp_summaries:
        longest = max(runs, default=0)
        label = "clean" if is_clean else "confounded, FP-on-normal-only"
        print(f"  {entity_id} ({label}): {fp_rate:.2%} false-positive rate on genuine drift behavior, "
              f"longest consecutive false-alarm run = {longest} event(s)")
    clean_entity_id, clean_fp_rate, clean_runs, _ = next(t for t in fp_summaries if t[3])
    print(
        f"\nOn the confirmed label-pure entity ({clean_entity_id}), the false-positive rate on genuine "
        f"drift behavior is {clean_fp_rate:.2%}, with a longest consecutive false-alarm run of "
        f"{max(clean_runs, default=0)} event(s): legitimate resource-footprint expansion does not sustain "
        f"a persistent false-alarm streak, because the hybrid alert rule scores every event independently "
        f"-- there is no streak-counter/persistence logic to chain isolated hits together.\n"
    )

    print("=== Feedback / retraining mechanism ===\n")
    print(
        "If an analyst repeatedly marks a drifted entity's alerts \"false_positive\" via the\n"
        "dashboard's verdict buttons (data/feedback.csv), that signal is ready for the next retrain:\n\n"
        "  1. Periodic retrain re-runs models/train.py on an updated chronological window -- since\n"
        "     each entity's baseline is always \"the first 60% of THAT entity's own recent history,\"\n"
        "     a role change or new project (like these drift entities) ages into the baseline\n"
        "     automatically once enough time has passed for it to dominate the entity's history.\n"
        "  2. Confirmed false positives from feedback.csv could be spliced directly into the next\n"
        "     baseline-building pass, so the newly-adopted resources stop being flagged as \"new\"\n"
        "     well before the natural chronological rollover would catch up.\n"
        "  3. Confirmed threats do the opposite -- excluded from ever entering a baseline, so an\n"
        "     attacker's early reconnaissance can't get absorbed as \"normal\" just because it\n"
        "     happened early in the window.\n\n"
        "This keeps the system's notion of \"normal\" moving with real organizational change\n"
        "without requiring a manual allowlist per entity."
    )


if __name__ == "__main__":
    main()
